### ISSUE TITLE
Incorrect score recorded on auto submit

### ISSUE THREAD

**Issue by codewitgabi** [codewitgabi/django_quiz_app#3]
When the time for a quiz elapses and the quiz is submitted, not all answers are sent to the API for submission thereby resulting in wrong results

**Comment by siufai6** [comment]
Tested on edge, it works fine with auto submitting answer when time is up.  
Tested on firefox, it gave a NS_BINDING_ABORT error (check on developer tool).  
![image](https://github.com/codewitgabi/django_quiz_app/assets/24217897/324b82c3-60b4-44df-a79f-e835599bc6ac)

**Comment by codewitgabi** [comment]
I tested on chrome and opera mini and it's not handling correctly. Note that even though the score is submitted, sometimes, not all are correct.

**Comment by siufai6** [comment]
I tested on IOS chrome and found there is a "Type Error: Load Fail" error.  But in fact the data is passed to backend successfully. So it is again some issues with the front end js.  
  I couldn't find opera mini on IOS so can only test it on android.

**Comment by siufai6** [comment]
issue was caused by the fact that the code (change eventhandler) stores the answers in localstorage using question id 
```
      localStorage.setItem(form.question_id.value, radioBtn.value);

```
but in submitAnswers function, the code checks for answers using sequence 
```
      ? (answers[`${i}`] = localStorage[`${i}`])
```

The problem shows in autosubmit and manual submit if there are more than 1 quiz in the system.
